languageCode = "es"
languageName = "Espa√±ol"
displayName = "ES"
isoCode = "es"
weight = 2
rtl = false

title = "Regreso a la Web 1.0"
# logo = "img/logo.png"
description = "Divagaciones de un Ingeniero con innumerables aficiones"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "J.M. Sousa"
  image = "img/octo-robot.jpg"
  headline = "No soy un robot"
  bio = "Ingeniero inquieto, escritor ocasional y desarrollador de videojuegos aficionado"
  links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
#     { mastodon = "https://mastodon.gamedev.place/@puzuma" },
#     { github = "https://github.com/jsousadacunha" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/puzuma_soft" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/jose-sousa" }
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { orcid = "https://orcid.org/userid" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { researchgate = "https://www.researchgate.net/profile/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  #   { ko-fi = "https://ko-fi.com/username" },
      { threads = "https://www.threads.net/@j.m.sousa" },
      { wattpad = "https://www.wattpad.com/user/j_m_sousa"}
  ]
